version: "3.7"

services:
  postgres:
    image: postgres
    container_name: db_app
    env_file:
      - .env-prod
    ports:
      - "5432:5432"
    volumes:
      - ./db/:/var/lib/postgresql/data

  app:
    build:
      context: .
    env_file:
      - .env-prod
    container_name: fastapi_app
    command: ["/python_advanced_diploma/docker/app.sh"]
    ports:
      - "8005:8000"
    volumes:
      - static_volume:/python_advanced_diploma/static
      - ./images:/images
    depends_on:
      - postgres

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - static_volume:/etc/nginx/html
      - ./images:/etc/nginx/html/images
    depends_on:
      - app

volumes:
  static_volume:
